// Code generated by "enumer -type=event -text -transform upper"; DO NOT EDIT.

package server

import (
	"fmt"
	"strings"
)

const _eventName = "INVALIDEVENTCONNECT"

var _eventIndex = [...]uint8{0, 12, 19}

const _eventLowerName = "invalideventconnect"

func (i event) String() string {
	if i < 0 || i >= event(len(_eventIndex)-1) {
		return fmt.Sprintf("event(%d)", i)
	}
	return _eventName[_eventIndex[i]:_eventIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _eventNoOp() {
	var x [1]struct{}
	_ = x[invalidEvent-(0)]
	_ = x[connect-(1)]
}

var _eventValues = []event{invalidEvent, connect}

var _eventNameToValueMap = map[string]event{
	_eventName[0:12]:       invalidEvent,
	_eventLowerName[0:12]:  invalidEvent,
	_eventName[12:19]:      connect,
	_eventLowerName[12:19]: connect,
}

var _eventNames = []string{
	_eventName[0:12],
	_eventName[12:19],
}

// eventString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func eventString(s string) (event, error) {
	if val, ok := _eventNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _eventNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to event values", s)
}

// eventValues returns all values of the enum
func eventValues() []event {
	return _eventValues
}

// eventStrings returns a slice of all String values of the enum
func eventStrings() []string {
	strs := make([]string, len(_eventNames))
	copy(strs, _eventNames)
	return strs
}

// IsAevent returns "true" if the value is listed in the enum definition. "false" otherwise
func (i event) IsAevent() bool {
	for _, v := range _eventValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for event
func (i event) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for event
func (i *event) UnmarshalText(text []byte) error {
	var err error
	*i, err = eventString(string(text))
	return err
}
