// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	go tool mockgen -source=handler.go -destination=handler_mock_test.go -package=age_test -write_generate_directive -prog_name=go tool mockgen
//

// Package age_test is a generated GoMock package.
package age_test

import (
	crypto "crypto"
	ecdh "crypto/ecdh"
	reflect "reflect"

	age "github.com/smlx/piv-agent/internal/age"
	gomock "go.uber.org/mock/gomock"
)

//go:generate go tool mockgen -source=handler.go -destination=handler_mock_test.go -package=age_test -write_generate_directive "-prog_name=go tool mockgen"

// MockECDHKey is a mock of ECDHKey interface.
type MockECDHKey struct {
	ctrl     *gomock.Controller
	recorder *MockECDHKeyMockRecorder
	isgomock struct{}
}

// MockECDHKeyMockRecorder is the mock recorder for MockECDHKey.
type MockECDHKeyMockRecorder struct {
	mock *MockECDHKey
}

// NewMockECDHKey creates a new mock instance.
func NewMockECDHKey(ctrl *gomock.Controller) *MockECDHKey {
	mock := &MockECDHKey{ctrl: ctrl}
	mock.recorder = &MockECDHKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECDHKey) EXPECT() *MockECDHKeyMockRecorder {
	return m.recorder
}

// ECDH mocks base method.
func (m *MockECDHKey) ECDH(peer *ecdh.PublicKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ECDH", peer)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ECDH indicates an expected call of ECDH.
func (mr *MockECDHKeyMockRecorder) ECDH(peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ECDH", reflect.TypeOf((*MockECDHKey)(nil).ECDH), peer)
}

// Public mocks base method.
func (m *MockECDHKey) Public() crypto.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Public")
	ret0, _ := ret[0].(crypto.PublicKey)
	return ret0
}

// Public indicates an expected call of Public.
func (mr *MockECDHKeyMockRecorder) Public() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Public", reflect.TypeOf((*MockECDHKey)(nil).Public))
}

// MockECDHService is a mock of ECDHService interface.
type MockECDHService struct {
	ctrl     *gomock.Controller
	recorder *MockECDHServiceMockRecorder
	isgomock struct{}
}

// MockECDHServiceMockRecorder is the mock recorder for MockECDHService.
type MockECDHServiceMockRecorder struct {
	mock *MockECDHService
}

// NewMockECDHService creates a new mock instance.
func NewMockECDHService(ctrl *gomock.Controller) *MockECDHService {
	mock := &MockECDHService{ctrl: ctrl}
	mock.recorder = &MockECDHServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECDHService) EXPECT() *MockECDHServiceMockRecorder {
	return m.recorder
}

// GetECDHKey mocks base method.
func (m *MockECDHService) GetECDHKey(serial, slotID uint32, keyTag [4]byte) (age.ECDHKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetECDHKey", serial, slotID, keyTag)
	ret0, _ := ret[0].(age.ECDHKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetECDHKey indicates an expected call of GetECDHKey.
func (mr *MockECDHServiceMockRecorder) GetECDHKey(serial, slotID, keyTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetECDHKey", reflect.TypeOf((*MockECDHService)(nil).GetECDHKey), serial, slotID, keyTag)
}
