// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package crypto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CryptoClient is the client API for Crypto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoClient interface {
	ListIdentities(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Identities, error)
	GenerateIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*EmptyReturn, error)
	Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*Ciphertext, error)
	Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*Cleartext, error)
	Name(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*ServerName, error)
	Version(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*ServerVersion, error)
	Initialized(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*EmptyReturn, error)
	Ext(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Extension, error)
	IDFile(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*IDFileName, error)
}

type cryptoClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoClient(cc grpc.ClientConnInterface) CryptoClient {
	return &cryptoClient{cc}
}

var cryptoListIdentitiesStreamDesc = &grpc.StreamDesc{
	StreamName: "ListIdentities",
}

func (c *cryptoClient) ListIdentities(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Identities, error) {
	out := new(Identities)
	err := c.cc.Invoke(ctx, "/Crypto/ListIdentities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoGenerateIdentityStreamDesc = &grpc.StreamDesc{
	StreamName: "GenerateIdentity",
}

func (c *cryptoClient) GenerateIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*EmptyReturn, error) {
	out := new(EmptyReturn)
	err := c.cc.Invoke(ctx, "/Crypto/GenerateIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoEncryptStreamDesc = &grpc.StreamDesc{
	StreamName: "Encrypt",
}

func (c *cryptoClient) Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*Ciphertext, error) {
	out := new(Ciphertext)
	err := c.cc.Invoke(ctx, "/Crypto/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoDecryptStreamDesc = &grpc.StreamDesc{
	StreamName: "Decrypt",
}

func (c *cryptoClient) Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*Cleartext, error) {
	out := new(Cleartext)
	err := c.cc.Invoke(ctx, "/Crypto/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoNameStreamDesc = &grpc.StreamDesc{
	StreamName: "Name",
}

func (c *cryptoClient) Name(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*ServerName, error) {
	out := new(ServerName)
	err := c.cc.Invoke(ctx, "/Crypto/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoVersionStreamDesc = &grpc.StreamDesc{
	StreamName: "Version",
}

func (c *cryptoClient) Version(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*ServerVersion, error) {
	out := new(ServerVersion)
	err := c.cc.Invoke(ctx, "/Crypto/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoInitializedStreamDesc = &grpc.StreamDesc{
	StreamName: "Initialized",
}

func (c *cryptoClient) Initialized(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*EmptyReturn, error) {
	out := new(EmptyReturn)
	err := c.cc.Invoke(ctx, "/Crypto/Initialized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoExtStreamDesc = &grpc.StreamDesc{
	StreamName: "Ext",
}

func (c *cryptoClient) Ext(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*Extension, error) {
	out := new(Extension)
	err := c.cc.Invoke(ctx, "/Crypto/Ext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var cryptoIDFileStreamDesc = &grpc.StreamDesc{
	StreamName: "IDFile",
}

func (c *cryptoClient) IDFile(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*IDFileName, error) {
	out := new(IDFileName)
	err := c.cc.Invoke(ctx, "/Crypto/IDFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoService is the service API for Crypto service.
// Fields should be assigned to their respective handler implementations only before
// RegisterCryptoService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type CryptoService struct {
	ListIdentities   func(context.Context, *EmptyArgs) (*Identities, error)
	GenerateIdentity func(context.Context, *Identity) (*EmptyReturn, error)
	Encrypt          func(context.Context, *EncryptArgs) (*Ciphertext, error)
	Decrypt          func(context.Context, *DecryptArgs) (*Cleartext, error)
	Name             func(context.Context, *EmptyArgs) (*ServerName, error)
	Version          func(context.Context, *EmptyArgs) (*ServerVersion, error)
	Initialized      func(context.Context, *EmptyArgs) (*EmptyReturn, error)
	Ext              func(context.Context, *EmptyArgs) (*Extension, error)
	IDFile           func(context.Context, *EmptyArgs) (*IDFileName, error)
}

func (s *CryptoService) listIdentities(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/ListIdentities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.ListIdentities(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) generateIdentity(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GenerateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/GenerateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GenerateIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) encrypt(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Encrypt(ctx, req.(*EncryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) decrypt(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Decrypt(ctx, req.(*DecryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) name(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Name(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) version(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Version(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) initialized(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Initialized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Initialized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Initialized(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) ext(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Ext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/Ext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Ext(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *CryptoService) iDFile(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.IDFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Crypto/IDFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.IDFile(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterCryptoService registers a service implementation with a gRPC server.
func RegisterCryptoService(s grpc.ServiceRegistrar, srv *CryptoService) {
	srvCopy := *srv
	if srvCopy.ListIdentities == nil {
		srvCopy.ListIdentities = func(context.Context, *EmptyArgs) (*Identities, error) {
			return nil, status.Errorf(codes.Unimplemented, "method ListIdentities not implemented")
		}
	}
	if srvCopy.GenerateIdentity == nil {
		srvCopy.GenerateIdentity = func(context.Context, *Identity) (*EmptyReturn, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GenerateIdentity not implemented")
		}
	}
	if srvCopy.Encrypt == nil {
		srvCopy.Encrypt = func(context.Context, *EncryptArgs) (*Ciphertext, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
		}
	}
	if srvCopy.Decrypt == nil {
		srvCopy.Decrypt = func(context.Context, *DecryptArgs) (*Cleartext, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
		}
	}
	if srvCopy.Name == nil {
		srvCopy.Name = func(context.Context, *EmptyArgs) (*ServerName, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
		}
	}
	if srvCopy.Version == nil {
		srvCopy.Version = func(context.Context, *EmptyArgs) (*ServerVersion, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
		}
	}
	if srvCopy.Initialized == nil {
		srvCopy.Initialized = func(context.Context, *EmptyArgs) (*EmptyReturn, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Initialized not implemented")
		}
	}
	if srvCopy.Ext == nil {
		srvCopy.Ext = func(context.Context, *EmptyArgs) (*Extension, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Ext not implemented")
		}
	}
	if srvCopy.IDFile == nil {
		srvCopy.IDFile = func(context.Context, *EmptyArgs) (*IDFileName, error) {
			return nil, status.Errorf(codes.Unimplemented, "method IDFile not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Crypto",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "ListIdentities",
				Handler:    srvCopy.listIdentities,
			},
			{
				MethodName: "GenerateIdentity",
				Handler:    srvCopy.generateIdentity,
			},
			{
				MethodName: "Encrypt",
				Handler:    srvCopy.encrypt,
			},
			{
				MethodName: "Decrypt",
				Handler:    srvCopy.decrypt,
			},
			{
				MethodName: "Name",
				Handler:    srvCopy.name,
			},
			{
				MethodName: "Version",
				Handler:    srvCopy.version,
			},
			{
				MethodName: "Initialized",
				Handler:    srvCopy.initialized,
			},
			{
				MethodName: "Ext",
				Handler:    srvCopy.ext,
			},
			{
				MethodName: "IDFile",
				Handler:    srvCopy.iDFile,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "crypto/crypto.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewCryptoService creates a new CryptoService containing the
// implemented methods of the Crypto service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewCryptoService(s interface{}) *CryptoService {
	ns := &CryptoService{}
	if h, ok := s.(interface {
		ListIdentities(context.Context, *EmptyArgs) (*Identities, error)
	}); ok {
		ns.ListIdentities = h.ListIdentities
	}
	if h, ok := s.(interface {
		GenerateIdentity(context.Context, *Identity) (*EmptyReturn, error)
	}); ok {
		ns.GenerateIdentity = h.GenerateIdentity
	}
	if h, ok := s.(interface {
		Encrypt(context.Context, *EncryptArgs) (*Ciphertext, error)
	}); ok {
		ns.Encrypt = h.Encrypt
	}
	if h, ok := s.(interface {
		Decrypt(context.Context, *DecryptArgs) (*Cleartext, error)
	}); ok {
		ns.Decrypt = h.Decrypt
	}
	if h, ok := s.(interface {
		Name(context.Context, *EmptyArgs) (*ServerName, error)
	}); ok {
		ns.Name = h.Name
	}
	if h, ok := s.(interface {
		Version(context.Context, *EmptyArgs) (*ServerVersion, error)
	}); ok {
		ns.Version = h.Version
	}
	if h, ok := s.(interface {
		Initialized(context.Context, *EmptyArgs) (*EmptyReturn, error)
	}); ok {
		ns.Initialized = h.Initialized
	}
	if h, ok := s.(interface {
		Ext(context.Context, *EmptyArgs) (*Extension, error)
	}); ok {
		ns.Ext = h.Ext
	}
	if h, ok := s.(interface {
		IDFile(context.Context, *EmptyArgs) (*IDFileName, error)
	}); ok {
		ns.IDFile = h.IDFile
	}
	return ns
}

// UnstableCryptoService is the service API for Crypto service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableCryptoService interface {
	ListIdentities(context.Context, *EmptyArgs) (*Identities, error)
	GenerateIdentity(context.Context, *Identity) (*EmptyReturn, error)
	Encrypt(context.Context, *EncryptArgs) (*Ciphertext, error)
	Decrypt(context.Context, *DecryptArgs) (*Cleartext, error)
	Name(context.Context, *EmptyArgs) (*ServerName, error)
	Version(context.Context, *EmptyArgs) (*ServerVersion, error)
	Initialized(context.Context, *EmptyArgs) (*EmptyReturn, error)
	Ext(context.Context, *EmptyArgs) (*Extension, error)
	IDFile(context.Context, *EmptyArgs) (*IDFileName, error)
}
