// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CryptoClient is the client API for Crypto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoClient interface {
	ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Identities, error)
	GenerateIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*Ciphertext, error)
	Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*Cleartext, error)
	Name(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerName, error)
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerVersion, error)
	Initialized(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Ext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Extension, error)
	IDFile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IDFileName, error)
}

type cryptoClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoClient(cc grpc.ClientConnInterface) CryptoClient {
	return &cryptoClient{cc}
}

func (c *cryptoClient) ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Identities, error) {
	out := new(Identities)
	err := c.cc.Invoke(ctx, "/Crypto/ListIdentities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) GenerateIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Crypto/GenerateIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*Ciphertext, error) {
	out := new(Ciphertext)
	err := c.cc.Invoke(ctx, "/Crypto/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*Cleartext, error) {
	out := new(Cleartext)
	err := c.cc.Invoke(ctx, "/Crypto/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Name(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerName, error) {
	out := new(ServerName)
	err := c.cc.Invoke(ctx, "/Crypto/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerVersion, error) {
	out := new(ServerVersion)
	err := c.cc.Invoke(ctx, "/Crypto/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Initialized(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Crypto/Initialized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Ext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Extension, error) {
	out := new(Extension)
	err := c.cc.Invoke(ctx, "/Crypto/Ext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) IDFile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IDFileName, error) {
	out := new(IDFileName)
	err := c.cc.Invoke(ctx, "/Crypto/IDFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServer is the server API for Crypto service.
// All implementations must embed UnimplementedCryptoServer
// for forward compatibility
type CryptoServer interface {
	ListIdentities(context.Context, *emptypb.Empty) (*Identities, error)
	GenerateIdentity(context.Context, *Identity) (*emptypb.Empty, error)
	Encrypt(context.Context, *EncryptArgs) (*Ciphertext, error)
	Decrypt(context.Context, *DecryptArgs) (*Cleartext, error)
	Name(context.Context, *emptypb.Empty) (*ServerName, error)
	Version(context.Context, *emptypb.Empty) (*ServerVersion, error)
	Initialized(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Ext(context.Context, *emptypb.Empty) (*Extension, error)
	IDFile(context.Context, *emptypb.Empty) (*IDFileName, error)
	mustEmbedUnimplementedCryptoServer()
}

// UnimplementedCryptoServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoServer struct {
}

func (UnimplementedCryptoServer) ListIdentities(context.Context, *emptypb.Empty) (*Identities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedCryptoServer) GenerateIdentity(context.Context, *Identity) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateIdentity not implemented")
}
func (UnimplementedCryptoServer) Encrypt(context.Context, *EncryptArgs) (*Ciphertext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedCryptoServer) Decrypt(context.Context, *DecryptArgs) (*Cleartext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedCryptoServer) Name(context.Context, *emptypb.Empty) (*ServerName, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedCryptoServer) Version(context.Context, *emptypb.Empty) (*ServerVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedCryptoServer) Initialized(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialized not implemented")
}
func (UnimplementedCryptoServer) Ext(context.Context, *emptypb.Empty) (*Extension, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ext not implemented")
}
func (UnimplementedCryptoServer) IDFile(context.Context, *emptypb.Empty) (*IDFileName, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IDFile not implemented")
}
func (UnimplementedCryptoServer) mustEmbedUnimplementedCryptoServer() {}

// UnsafeCryptoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServer will
// result in compilation errors.
type UnsafeCryptoServer interface {
	mustEmbedUnimplementedCryptoServer()
}

func RegisterCryptoServer(s grpc.ServiceRegistrar, srv CryptoServer) {
	s.RegisterService(&_Crypto_serviceDesc, srv)
}

func _Crypto_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/ListIdentities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).ListIdentities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_GenerateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).GenerateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/GenerateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).GenerateIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Encrypt(ctx, req.(*EncryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Decrypt(ctx, req.(*DecryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Name(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Initialized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Initialized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Initialized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Initialized(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Ext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Ext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/Ext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Ext(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_IDFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).IDFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto/IDFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).IDFile(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Crypto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Crypto",
	HandlerType: (*CryptoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIdentities",
			Handler:    _Crypto_ListIdentities_Handler,
		},
		{
			MethodName: "GenerateIdentity",
			Handler:    _Crypto_GenerateIdentity_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _Crypto_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _Crypto_Decrypt_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _Crypto_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Crypto_Version_Handler,
		},
		{
			MethodName: "Initialized",
			Handler:    _Crypto_Initialized_Handler,
		},
		{
			MethodName: "Ext",
			Handler:    _Crypto_Ext_Handler,
		},
		{
			MethodName: "IDFile",
			Handler:    _Crypto_IDFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/crypto.proto",
}
