// Code generated by MockGen. DO NOT EDIT.
// Source: crypto.go

// Package mock is a generated GoMock package.
package mock

import (
	crypto "crypto"
	gomock "github.com/golang/mock/gomock"
	ssh "golang.org/x/crypto/ssh"
	reflect "reflect"
)

// MockAgent is a mock of Agent interface
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
}

// MockAgentMockRecorder is the mock recorder for MockAgent
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// PublicKeys mocks base method
func (m *MockAgent) PublicKeys() ([]ssh.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKeys")
	ret0, _ := ret[0].([]ssh.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicKeys indicates an expected call of PublicKeys
func (mr *MockAgentMockRecorder) PublicKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKeys", reflect.TypeOf((*MockAgent)(nil).PublicKeys))
}

// SharedKey mocks base method
func (m *MockAgent) SharedKey(recipient, peer crypto.PublicKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SharedKey", recipient, peer)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SharedKey indicates an expected call of SharedKey
func (mr *MockAgentMockRecorder) SharedKey(recipient, peer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SharedKey", reflect.TypeOf((*MockAgent)(nil).SharedKey), recipient, peer)
}
