// Code generated by MockGen. DO NOT EDIT.
// Source: assuan.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	key "github.com/smlx/piv-agent/internal/key"
	reflect "reflect"
)

// MockPIVAgent is a mock of PIVAgent interface
type MockPIVAgent struct {
	ctrl     *gomock.Controller
	recorder *MockPIVAgentMockRecorder
}

// MockPIVAgentMockRecorder is the mock recorder for MockPIVAgent
type MockPIVAgentMockRecorder struct {
	mock *MockPIVAgent
}

// NewMockPIVAgent creates a new mock instance
func NewMockPIVAgent(ctrl *gomock.Controller) *MockPIVAgent {
	mock := &MockPIVAgent{ctrl: ctrl}
	mock.recorder = &MockPIVAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPIVAgent) EXPECT() *MockPIVAgentMockRecorder {
	return m.recorder
}

// SecurityKeys mocks base method
func (m *MockPIVAgent) SecurityKeys() ([]key.Security, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecurityKeys")
	ret0, _ := ret[0].([]key.Security)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecurityKeys indicates an expected call of SecurityKeys
func (mr *MockPIVAgentMockRecorder) SecurityKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityKeys", reflect.TypeOf((*MockPIVAgent)(nil).SecurityKeys))
}
