// Code generated by MockGen. DO NOT EDIT.
// Source: assuan.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pivservice "github.com/smlx/piv-agent/internal/pivservice"
)

// MockPIVService is a mock of PIVService interface.
type MockPIVService struct {
	ctrl     *gomock.Controller
	recorder *MockPIVServiceMockRecorder
}

// MockPIVServiceMockRecorder is the mock recorder for MockPIVService.
type MockPIVServiceMockRecorder struct {
	mock *MockPIVService
}

// NewMockPIVService creates a new mock instance.
func NewMockPIVService(ctrl *gomock.Controller) *MockPIVService {
	mock := &MockPIVService{ctrl: ctrl}
	mock.recorder = &MockPIVServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPIVService) EXPECT() *MockPIVServiceMockRecorder {
	return m.recorder
}

// SecurityKeys mocks base method.
func (m *MockPIVService) SecurityKeys() ([]pivservice.SecurityKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecurityKeys")
	ret0, _ := ret[0].([]pivservice.SecurityKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecurityKeys indicates an expected call of SecurityKeys.
func (mr *MockPIVServiceMockRecorder) SecurityKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityKeys", reflect.TypeOf((*MockPIVService)(nil).SecurityKeys))
}
