// Code generated by "enumer -type=HashAlgo"; DO NOT EDIT.

package assuan

import (
	"fmt"
	"strings"
)

const (
	_HashAlgoName_0      = "invalidHash"
	_HashAlgoLowerName_0 = "invalidhash"
	_HashAlgoName_1      = "sha512"
	_HashAlgoLowerName_1 = "sha512"
)

var (
	_HashAlgoIndex_0 = [...]uint8{0, 11}
	_HashAlgoIndex_1 = [...]uint8{0, 6}
)

func (i HashAlgo) String() string {
	switch {
	case i == 0:
		return _HashAlgoName_0
	case i == 10:
		return _HashAlgoName_1
	default:
		return fmt.Sprintf("HashAlgo(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HashAlgoNoOp() {
	var x [1]struct{}
	_ = x[invalidHash-(0)]
	_ = x[sha512-(10)]
}

var _HashAlgoValues = []HashAlgo{invalidHash, sha512}

var _HashAlgoNameToValueMap = map[string]HashAlgo{
	_HashAlgoName_0[0:11]:      invalidHash,
	_HashAlgoLowerName_0[0:11]: invalidHash,
	_HashAlgoName_1[0:6]:       sha512,
	_HashAlgoLowerName_1[0:6]:  sha512,
}

var _HashAlgoNames = []string{
	_HashAlgoName_0[0:11],
	_HashAlgoName_1[0:6],
}

// HashAlgoString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HashAlgoString(s string) (HashAlgo, error) {
	if val, ok := _HashAlgoNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _HashAlgoNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HashAlgo values", s)
}

// HashAlgoValues returns all values of the enum
func HashAlgoValues() []HashAlgo {
	return _HashAlgoValues
}

// HashAlgoStrings returns a slice of all String values of the enum
func HashAlgoStrings() []string {
	strs := make([]string, len(_HashAlgoNames))
	copy(strs, _HashAlgoNames)
	return strs
}

// IsAHashAlgo returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HashAlgo) IsAHashAlgo() bool {
	for _, v := range _HashAlgoValues {
		if i == v {
			return true
		}
	}
	return false
}
