// Code generated by MockGen. DO NOT EDIT.
// Source: assuan_test.go
//
// Generated by this command:
//
//	mockgen -source=assuan_test.go -destination=mock_securitykey_test.go -package=assuan_test
//

// Package assuan_test is a generated GoMock package.
package assuan_test

import (
	reflect "reflect"

	securitykey "github.com/smlx/piv-agent/internal/securitykey"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityKey is a mock of SecurityKey interface.
type MockSecurityKey struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityKeyMockRecorder
	isgomock struct{}
}

// MockSecurityKeyMockRecorder is the mock recorder for MockSecurityKey.
type MockSecurityKeyMockRecorder struct {
	mock *MockSecurityKey
}

// NewMockSecurityKey creates a new mock instance.
func NewMockSecurityKey(ctrl *gomock.Controller) *MockSecurityKey {
	mock := &MockSecurityKey{ctrl: ctrl}
	mock.recorder = &MockSecurityKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityKey) EXPECT() *MockSecurityKeyMockRecorder {
	return m.recorder
}

// SigningKeys mocks base method.
func (m *MockSecurityKey) SigningKeys() []securitykey.SigningKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SigningKeys")
	ret0, _ := ret[0].([]securitykey.SigningKey)
	return ret0
}

// SigningKeys indicates an expected call of SigningKeys.
func (mr *MockSecurityKeyMockRecorder) SigningKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigningKeys", reflect.TypeOf((*MockSecurityKey)(nil).SigningKeys))
}
