// Code generated by MockGen. DO NOT EDIT.
// Source: assuan_test.go
//
// Generated by this command:
//
//	go tool mockgen -source=assuan_test.go -destination=securitykey_mock_test.go -package=assuan_test -write_generate_directive -prog_name=go tool mockgen
//

// Package assuan_test is a generated GoMock package.
package assuan_test

import (
	reflect "reflect"

	securitykey "github.com/smlx/piv-agent/internal/securitykey"
	gomock "go.uber.org/mock/gomock"
)

//go:generate go tool mockgen -source=assuan_test.go -destination=securitykey_mock_test.go -package=assuan_test -write_generate_directive "-prog_name=go tool mockgen"

// MockSecurityKey is a mock of SecurityKey interface.
type MockSecurityKey struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityKeyMockRecorder
	isgomock struct{}
}

// MockSecurityKeyMockRecorder is the mock recorder for MockSecurityKey.
type MockSecurityKeyMockRecorder struct {
	mock *MockSecurityKey
}

// NewMockSecurityKey creates a new mock instance.
func NewMockSecurityKey(ctrl *gomock.Controller) *MockSecurityKey {
	mock := &MockSecurityKey{ctrl: ctrl}
	mock.recorder = &MockSecurityKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityKey) EXPECT() *MockSecurityKeyMockRecorder {
	return m.recorder
}

// SigningKeys mocks base method.
func (m *MockSecurityKey) SigningKeys() []securitykey.SigningKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SigningKeys")
	ret0, _ := ret[0].([]securitykey.SigningKey)
	return ret0
}

// SigningKeys indicates an expected call of SigningKeys.
func (mr *MockSecurityKeyMockRecorder) SigningKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigningKeys", reflect.TypeOf((*MockSecurityKey)(nil).SigningKeys))
}

// MockPINEntryService is a mock of PINEntryService interface.
type MockPINEntryService struct {
	ctrl     *gomock.Controller
	recorder *MockPINEntryServiceMockRecorder
	isgomock struct{}
}

// MockPINEntryServiceMockRecorder is the mock recorder for MockPINEntryService.
type MockPINEntryServiceMockRecorder struct {
	mock *MockPINEntryService
}

// NewMockPINEntryService creates a new mock instance.
func NewMockPINEntryService(ctrl *gomock.Controller) *MockPINEntryService {
	mock := &MockPINEntryService{ctrl: ctrl}
	mock.recorder = &MockPINEntryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPINEntryService) EXPECT() *MockPINEntryServiceMockRecorder {
	return m.recorder
}

// GetPassphrase mocks base method.
func (m *MockPINEntryService) GetPassphrase(arg0, arg1 string, arg2 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassphrase", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassphrase indicates an expected call of GetPassphrase.
func (mr *MockPINEntryServiceMockRecorder) GetPassphrase(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassphrase", reflect.TypeOf((*MockPINEntryService)(nil).GetPassphrase), arg0, arg1, arg2)
}
