// Code generated by "enumer -type=state -text -transform upper"; DO NOT EDIT.

package assuan

import (
	"fmt"
	"strings"
)

const _stateName = "INVALIDSTATEREADYCONNECTED"

var _stateIndex = [...]uint8{0, 12, 17, 26}

const _stateLowerName = "invalidstatereadyconnected"

func (i state) String() string {
	if i < 0 || i >= state(len(_stateIndex)-1) {
		return fmt.Sprintf("state(%d)", i)
	}
	return _stateName[_stateIndex[i]:_stateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _stateNoOp() {
	var x [1]struct{}
	_ = x[invalidState-(0)]
	_ = x[ready-(1)]
	_ = x[connected-(2)]
}

var _stateValues = []state{invalidState, ready, connected}

var _stateNameToValueMap = map[string]state{
	_stateName[0:12]:       invalidState,
	_stateLowerName[0:12]:  invalidState,
	_stateName[12:17]:      ready,
	_stateLowerName[12:17]: ready,
	_stateName[17:26]:      connected,
	_stateLowerName[17:26]: connected,
}

var _stateNames = []string{
	_stateName[0:12],
	_stateName[12:17],
	_stateName[17:26],
}

// stateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func stateString(s string) (state, error) {
	if val, ok := _stateNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _stateNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to state values", s)
}

// stateValues returns all values of the enum
func stateValues() []state {
	return _stateValues
}

// stateStrings returns a slice of all String values of the enum
func stateStrings() []string {
	strs := make([]string, len(_stateNames))
	copy(strs, _stateNames)
	return strs
}

// IsAstate returns "true" if the value is listed in the enum definition. "false" otherwise
func (i state) IsAstate() bool {
	for _, v := range _stateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for state
func (i state) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for state
func (i *state) UnmarshalText(text []byte) error {
	var err error
	*i, err = stateString(string(text))
	return err
}
