name: coverage
on:
  push:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: stable
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get -u install libpcsclite-dev
    - name: Calculate coverage
      run: |
        go test -count=1 -v -covermode=atomic -coverprofile=cover.out -coverpkg=./... ./...
    - name: Generage coverage badge
      uses: vladopajic/go-test-coverage@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2.18.8
      with:
        profile: cover.out
        local-prefix: github.com/${{ github.repository }}
        git-token: ${{ secrets.GITHUB_TOKEN }}
        # orphan branch for storing badges
        git-branch: badges
